blank_issues_enabled: false # Forces users to use a template
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/elwinjyot/nethop/discussions
    about: Please ask questions or share ideas in our GitHub Discussions!
